spring:
  application:
    name: helloconsumer
server:
  port: 7211
eureka:
  client:
    serviceUrl:
      defaultZone: http://114.116.129.54:30071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    preferIpAddress: true
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false   
helloconsumer:
  ribbon:
    NIWSServerListClassName: org.apache.servicecomb.springboot.starter.discovery.ServiceCombServerList
    
cse:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com:443
  config:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com:443

  credentials:
    accessKey: 2YJOW5CHCSHNKUCCJMPP
    secretKey: Qk3PGS6ArqXc0schaAYfrUait7BtzKhxpx4ifk48
    akskCustomCipher: default