spring:
  application:
    name: helloprovider

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://114.116.129.54:30071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

cse:
  service:
    registry:
      address: https://cse.cn-north-1.myhuaweicloud.com:443
  config:
    client:
      serverUri: https://cse.cn-north-1.myhuaweicloud.com:443
  credentials:
    accessKey: 2YJOW5CHCSHNKUCCJMPP
    secretKey: Qk3PGS6ArqXc0schaAYfrUait7BtzKhxpx4ifk48
    akskCustomCipher: default