spring:
  application:
    name: helloprovider

server:
  port: 7111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

cse:
  credentials:
    accessKey: 2YJOW5CHCSHNKUCCJMPP
    secretKey: Qk3PGS6ArqXc0schaAYfrUait7BtzKhxpx4ifk48
    akskCustomCipher: default